"""Project directory and git management."""

from __future__ import annotations

import subprocess
from pathlib import Path

import click


class Project:
    """Manages the generated project directory and git operations."""

    def __init__(self, path: Path, timeout: int = 30) -> None:
        self.path = path
        self.timeout = timeout

    def init(self, name: str) -> None:
        """Create project directory and initialize a git repo."""
        self.path.mkdir(parents=True, exist_ok=True)
        self._git("init")
        # Create initial commit so we have something to revert to
        readme = self.path / "README.md"
        readme.write_text(f"# {name}\n\nGenerated by Autoforge.\n")
        self._git("add", ".")
        self._git("commit", "-m", "Initial commit")

    def commit(self, message: str) -> bool:
        """Stage all changes and commit. Returns True if there were changes to commit."""
        self._git("add", ".")
        result = self._git("status", "--porcelain", capture=True)
        if not result.stdout.strip():
            return False
        self._git("commit", "-m", message)
        return True

    def revert(self) -> None:
        """Revert the last commit."""
        self._git("revert", "HEAD", "--no-edit")

    def get_diff(self) -> str:
        """Get the diff of uncommitted changes."""
        result = self._git("diff", capture=True)
        return result.stdout

    def get_last_diff(self) -> str:
        """Get the diff of the last commit."""
        result = self._git("diff", "HEAD~1", "HEAD", capture=True)
        return result.stdout

    def install_deps(self) -> bool:
        """Detect and install project dependencies. Returns True if deps were installed."""
        req_file = self.path / "requirements.txt"
        pkg_json = self.path / "package.json"

        if req_file.exists():
            click.echo("  Installing Python dependencies...")
            try:
                subprocess.run(
                    ["pip", "install", "-r", str(req_file), "--break-system-packages", "-q"],
                    cwd=self.path,
                    timeout=self.timeout * 2,
                    capture_output=True,
                    text=True,
                )
                return True
            except (subprocess.TimeoutExpired, FileNotFoundError) as e:
                click.echo(f"  Warning: dependency install failed: {e}")
                return False

        if pkg_json.exists():
            click.echo("  Installing Node dependencies...")
            try:
                subprocess.run(
                    ["npm", "install", "--silent"],
                    cwd=self.path,
                    timeout=self.timeout * 2,
                    capture_output=True,
                    text=True,
                )
                return True
            except (subprocess.TimeoutExpired, FileNotFoundError) as e:
                click.echo(f"  Warning: dependency install failed: {e}")
                return False

        return False

    def read_file(self, rel_path: str) -> str | None:
        """Read a file from the project. Returns None if not found."""
        full_path = self.path / rel_path
        if full_path.exists():
            return full_path.read_text()
        return None

    def write_file(self, rel_path: str, content: str) -> None:
        """Write a file to the project, creating directories as needed."""
        full_path = self.path / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)

    def list_files(self) -> list[str]:
        """List all tracked files in the project."""
        result = self._git("ls-files", capture=True)
        return [line for line in result.stdout.strip().splitlines() if line]

    def _git(self, *args: str, capture: bool = False) -> subprocess.CompletedProcess:
        """Run a git command in the project directory."""
        cmd = ["git"] + list(args)
        return subprocess.run(
            cmd,
            cwd=self.path,
            timeout=self.timeout,
            capture_output=capture or True,
            text=True,
        )
